### ISSUE TITLE
i want to change sdk but android works fine

### ISSUE THREAD

**Issue by Youjiro679** [Skyblueborb/ih8sn_laurel_sprout#1]
i try to change

ro.build.version.sdk = 28
ro.system.build.version.sdk = 28
ro.vendor.build.version.sdk = 28
ro.product.build.version.sdk = 28
ro.odm.build.version.sdk = 28
ro.system_ext.build.version.sdk = 28

but the applications are not working properly, is there any way to change the sdk and the application will still work, thanks

**Comment by Skyblueborb** [comment]
ih8sn doesn't support changing the SDK values, only the values listed in ih8sn.conf. I don't know of any way of changing the SDK version, sorry
